//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devir.DMS.Web.FullTextSearch {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFTS.FoundDocuments", Namespace="http://schemas.datacontract.org/2004/07/Devir.DMS.FulltextSearchEngine")]
    [System.SerializableAttribute()]
    public partial class ServiceFTSFoundDocuments : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocId {
            get {
                return this.DocIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIdField, value) != true)) {
                    this.DocIdField = value;
                    this.RaisePropertyChanged("DocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FullTextSearch.ServiceFTS")]
    public interface ServiceFTS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceFTS/SaveDocument", ReplyAction="http://tempuri.org/ServiceFTS/SaveDocumentResponse")]
        bool SaveDocument(System.Guid docId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceFTS/SaveDocument", ReplyAction="http://tempuri.org/ServiceFTS/SaveDocumentResponse")]
        System.Threading.Tasks.Task<bool> SaveDocumentAsync(System.Guid docId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceFTS/SearchDocuments", ReplyAction="http://tempuri.org/ServiceFTS/SearchDocumentsResponse")]
        System.Collections.Generic.List<Devir.DMS.Web.FullTextSearch.ServiceFTSFoundDocuments> SearchDocuments(string Text, string userId, string typeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceFTS/SearchDocuments", ReplyAction="http://tempuri.org/ServiceFTS/SearchDocumentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Devir.DMS.Web.FullTextSearch.ServiceFTSFoundDocuments>> SearchDocumentsAsync(string Text, string userId, string typeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceFTSChannel : Devir.DMS.Web.FullTextSearch.ServiceFTS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceFTSClient : System.ServiceModel.ClientBase<Devir.DMS.Web.FullTextSearch.ServiceFTS>, Devir.DMS.Web.FullTextSearch.ServiceFTS {
        
        public ServiceFTSClient() {
        }
        
        public ServiceFTSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceFTSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFTSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFTSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveDocument(System.Guid docId) {
            return base.Channel.SaveDocument(docId);
        }
        
        public System.Threading.Tasks.Task<bool> SaveDocumentAsync(System.Guid docId) {
            return base.Channel.SaveDocumentAsync(docId);
        }
        
        public System.Collections.Generic.List<Devir.DMS.Web.FullTextSearch.ServiceFTSFoundDocuments> SearchDocuments(string Text, string userId, string typeId) {
            return base.Channel.SearchDocuments(Text, userId, typeId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Devir.DMS.Web.FullTextSearch.ServiceFTSFoundDocuments>> SearchDocumentsAsync(string Text, string userId, string typeId) {
            return base.Channel.SearchDocumentsAsync(Text, userId, typeId);
        }
    }
}
