//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18213
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devir.DMS.OfficeToPDFConverter.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service1.FoundDocuments", Namespace="http://schemas.datacontract.org/2004/07/Devir.DMS.FulltextSearchEngine")]
    [System.SerializableAttribute()]
    public partial class Service1FoundDocuments : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISearchEngine")]
    public interface ISearchEngine {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchEngine/SaveDocument", ReplyAction="http://tempuri.org/ISearchEngine/SaveDocumentResponse")]
        bool SaveDocument(System.Guid docId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchEngine/SaveDocument", ReplyAction="http://tempuri.org/ISearchEngine/SaveDocumentResponse")]
        System.Threading.Tasks.Task<bool> SaveDocumentAsync(System.Guid docId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchEngine/SearchDocuments", ReplyAction="http://tempuri.org/ISearchEngine/SearchDocumentsResponse")]
        Devir.DMS.OfficeToPDFConverter.ServiceReference1.Service1FoundDocuments[] SearchDocuments(string Text, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchEngine/SearchDocuments", ReplyAction="http://tempuri.org/ISearchEngine/SearchDocumentsResponse")]
        System.Threading.Tasks.Task<Devir.DMS.OfficeToPDFConverter.ServiceReference1.Service1FoundDocuments[]> SearchDocumentsAsync(string Text, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchEngine/GetDataFromDocument", ReplyAction="http://tempuri.org/ISearchEngine/GetDataFromDocumentResponse")]
        string GetDataFromDocument(string Path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchEngine/GetDataFromDocument", ReplyAction="http://tempuri.org/ISearchEngine/GetDataFromDocumentResponse")]
        System.Threading.Tasks.Task<string> GetDataFromDocumentAsync(string Path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchEngineChannel : Devir.DMS.OfficeToPDFConverter.ServiceReference1.ISearchEngine, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchEngineClient : System.ServiceModel.ClientBase<Devir.DMS.OfficeToPDFConverter.ServiceReference1.ISearchEngine>, Devir.DMS.OfficeToPDFConverter.ServiceReference1.ISearchEngine {
        
        public SearchEngineClient() {
        }
        
        public SearchEngineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchEngineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchEngineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchEngineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveDocument(System.Guid docId) {
            return base.Channel.SaveDocument(docId);
        }
        
        public System.Threading.Tasks.Task<bool> SaveDocumentAsync(System.Guid docId) {
            return base.Channel.SaveDocumentAsync(docId);
        }
        
        public Devir.DMS.OfficeToPDFConverter.ServiceReference1.Service1FoundDocuments[] SearchDocuments(string Text, string userId) {
            return base.Channel.SearchDocuments(Text, userId);
        }
        
        public System.Threading.Tasks.Task<Devir.DMS.OfficeToPDFConverter.ServiceReference1.Service1FoundDocuments[]> SearchDocumentsAsync(string Text, string userId) {
            return base.Channel.SearchDocumentsAsync(Text, userId);
        }
        
        public string GetDataFromDocument(string Path) {
            return base.Channel.GetDataFromDocument(Path);
        }
        
        public System.Threading.Tasks.Task<string> GetDataFromDocumentAsync(string Path) {
            return base.Channel.GetDataFromDocumentAsync(Path);
        }
    }
}
